spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm_database?useSSL=false
    username: root
    password: Asdf123@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use-new-id-generator-mappings: false
server:
  port: 8090
